name: Basic Unity Build

on:
    pull_request:
      branches-ignore: master
      types: [opened, synchronize, reopened]
      paths-ignore:
        - README.md
    push: { branches: [main] }
    workflow_dispatch:

env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
    buildAndTest:
        name: Build and test in ${{ matrix.testMode }} on version ${{ matrix.unityVersion }}
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
            unityVersion:
              - 2020.1.11f1
            testMode:
              - playmode
              - editmode
            targetPlatform:
              - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
              - StandaloneWindows64 # Build a Windows 64-bit standalone.
              #- StandaloneLinux64 # Build a Linux 64-bit standalone.
              #- iOS # Build an iOS player.
              #- Android # Build an Android .apk standalone app.
              #- WebGL # WebGL.

        steps:
            # Checkout
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                lfs: true

            # Cache
            - name: Cache library files
              uses: actions/cache@v1.1.0
              with:
                path: Library
                key: Library

            # Test
            - name: Run editor and play mode tests
              uses: webbertakken/unity-test-runner@v1.7
              id: tests
              with:
                unityVersion: ${{ matrix.unityVersion }}
                testMode: ${{ matrix.testMode }}
                artifactsPath: ${{ matrix.testMode }}-artifacts

            # Upload Test Results
            - uses: actions/upload-artifact@v1
              with:
                name: Test results for ${{ matrix.testMode }}
                path: ${{ steps.tests.outputs.artifactsPath }}

            # Build
            - name: Build project
              uses: webbertakken/unity-builder@v1.5
              with:
                unityVersion: ${{ matrix.unityVersion }}
                targetPlatform: ${{ matrix.targetPlatform }}

            # Output
            - uses: actions/upload-artifact@v1
              with:
                name: Build
                path: build
